### ISSUE TITLE
Let me see all of my read books

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#112]
As a user I would like to see all my read books in a nice overview and with extra details if I want to. With this I can look up already read books and their details and do not have to look into the json file.

**Comment by Husterknupp** [comment]
![image](https://user-images.githubusercontent.com/1265382/145994049-be6386d6-7986-4762-85c2-cc9937fcd69b.png)

@Bantolomeus that's my first draft (nothing implemented, just Photoshop magic). My idea is that instead of focusing on only the pages that you've read today, we're showing your complete books library. 

Image Explanation:

1) The navbar would read "Challenge" and "Books", where Challenge shows the former Overall page and Books the former Today page
2) Optional: A new _Pinned Books_ section helps with a big library (I imagined you might be annoyed having to search for a book before you can add the pages you read today -- but we can also leave it out at first if that is not so much an issue)
3) Basically this will be a mirror of your `books.json`, not hiding completed books anymore. There will be no toggle and no extra page or so.  Completed and in-progress-books all on the same page, just like your physical library/book shelf.

Would that be helpful?

**Comment by Bantolomeus** [comment]
Option 1 sounds promising. But I would like to have the books that are not finished to be on top in the "Books" Page. Like with the pinned Books, but without pinned (I do not want to pin my books, the currently not finished books shall simply be in the upper part). The lower part should not contain the books that are currently read (unfinished).

**Comment by Husterknupp** [comment]
Here is what we just discussed in addition:

- No "pinned" list, but two lists on the same page. One list shows the currently read books the other shows all books that are completed already.
- less details for the read books tiles (title only)
- Detail-Ansicht in a seperate ticket
- Proper app Icon (book/bookmark) and remove link

**Comment by Husterknupp** [comment]
## Preview

![image](https://user-images.githubusercontent.com/1265382/149116859-610378f9-46d3-44aa-97c5-2b5f1ebc6ff0.png)

Hey @Bantolomeus the feature is ready for testing. Find [the jar here](https://github.com/Bantolomeus/bookmaster4000mkii/actions/runs/1686935801). I did everything on the master branch, that was not on purpose - maybe somehow thought I'm the only one around here anyway. Will work on a branch the next time

If you want to see what changed, take a look at [this comparison](https://github.com/Bantolomeus/bookmaster4000mkii/compare/d8a62a4...master).

I decided for a very flat, text-like list of the books that you've read because it's the most compact way I could think of while still maintaining some readability.

Also, the link names in the navigation bar didn't change because renaming would have included renaming occurrences in the code and there are a lot. And it's more a nice-to-have feature which can wait a bit. With the language change I want to do soon, that might be a better moment for renaming since I will touch those places anyway.

**Comment by Bantolomeus** [comment]
![BookmasterListOfReadBooks](https://user-images.githubusercontent.com/1318613/149180600-944d4384-2fa7-4623-8994-29ce715690e6.PNG)
I like it =)
I updated a book twice and it worked as intended. I will call you if I find a bug. For now I see no problems. The book icon is especially great =D
Link names change in the next ticket is fine with me, not that I can change it anyway xD But thanks for letting me know.
