### ISSUE TITLE
Update jquery and bootstrap

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#75]
To remove vulnerabilities JQuery and bootstrap should be updated

**Comment by Husterknupp** [comment]
broke the layout on my branch. Commiting here to have the updates combined

**Comment by Husterknupp** [comment]
![image](https://user-images.githubusercontent.com/1265382/47392083-cc829980-d71b-11e8-98bb-c30660b1f8b4.png)

@Bantolomeus btw, this is how the UI (even the tiny little bit that's on master) looks like if you'd have replaced the css link in the `index.html` to use Bootstrap 4. But you didn't that's why you didn't see a change. What you did was replacing only the javascript part of Bootstrap, not the css part. The latter one brought many major changes though. Will do this now

**Comment by Husterknupp** [comment]
at least until you know what to test for a change that you're doing?

**Comment by Husterknupp** [comment]
blocked by #71 (adopted the ui on the branch. Cherry picking is not trivial though. So let’s keep this open until the branch is merged to master)

**Comment by Husterknupp** [comment]
#71 was just done
