### ISSUE TITLE
Vulnerability in webpack-dev-server

### ISSUE THREAD

**Issue by Bantolomeus** [Bantolomeus/bookmaster4000mkii#89]
@Husterknupp I got this message after updating npm:
![image](https://user-images.githubusercontent.com/1318613/48304931-9c603680-e522-11e8-8bb8-d95edb790bc4.png)

I would like to have this fixed, but I do not want to break the frontend again because a lack of knowledge on my side.
What do you suggest?

**Comment by Husterknupp** [comment]
🙌 thx for asking 🙌 (wonder why you always find the security holes 🤔

you should be safe executing the suggested `npm install [..]` command. Expect a change in the package.json afterwards and please commit it to master.

Am 10.11.2018 um 19:58 schrieb Christian Bantel <notifications@github.com<mailto:notifications@github.com>>:


@Husterknupp<https://github.com/Husterknupp> I got this message after updating npm:
[image]<https://user-images.githubusercontent.com/1318613/48304931-9c603680-e522-11e8-8bb8-d95edb790bc4.png>

I would like to have this fixed, but I do not want to break the frontend again because a lack of knowledge on my side.
What do you suggest?

**Comment by Bantolomeus** [comment]
My bad, as you can see in the screenshot it is on the review branch, in master I do not get the vulnerability warning. I will close the ticket without doing anything because master is fine. But thanks for the fast and helpful (no sarcasm) reply.
